### ISSUE TITLE
PiHole was working now it is having DNS issues

### ISSUE THREAD

**Issue by sudo-kraken** [adradloff/docker-HTPC#3]
I had it up and running for a day or two then on a reboot the pihole container keeps erroring stating that the nameserver in /etc/resolv.conf is 127.0.0.11 which is wrong, I have tried to swap out the environment variables for this:
    dns:
      - 127.0.0.1
      - 1.1.1.1
which is what was advised by the oracles or reddit but it had no luck, I cant work out why this has changed and stopped working.

Also on an unrelated note once I get this working again is there a way to get pihole to work with cloudflared for dnssec I noticed this was commented out in your yml file and was wondering if it is possible to do with treafik etc without defining ipv4 addresses as usually when I do that and restart my containers it says the address is already in use.

Apologies if this is the wrong forum.

**Comment by g0ldfngr** [comment]
In my resolv.conf, I have the actual LAN IP address of my server 'nameserver 192.168.1.10' as an example. can you try changing yours to that and see if that works?

I removed cloudeflared as it doesn't allow me to use to use DNS 1.0.0.2 for secure yet.  1.0.0.2 allows for filtering out known malware sites and is a cloudflare DNS server.  It should work if you enable it.  If not open it up under a new issue and I will resolve as I get time.

**Comment by sudo-kraken** [comment]
in your resolvconf are you refering to the one in the pihole container? if so you cant edit this ?. Would you be able to tell me how to get it working with pihole once I get pihole up or does the commented out config in your yml work ?

**Comment by g0ldfngr** [comment]
This is the resolve.conf on my host server. not in the pihole container.

**Comment by sudo-kraken** [comment]
the one in my host server is my router ip

**Comment by sudo-kraken** [comment]
so far I have run these commands
sudo systemctl disable systemd-resolved.service
sudo systemctl stop systemd-resolved.service
sudo nano /etc/NetworkManager/NetworkManager.conf
added dns=default 
sudo mv /etc/resolv.conf /etc/resolv.conf.bak
sudo service network-manager restart
The used the same setup as you in your compose file for pihole but without ip addresses as when I tried it with them when the container restarted it said the ips were in use everytime, but now a few days later pihole stopped working and started complaining about 127.0.0.11 which if you bash into the pihole container and check out /etc/resolv.conf it has nameserver = 127.0.0.11 and then wont start up.

**Comment by sudo-kraken** [comment]
I noticed that your yml for pihole had this
      - DNS1=1.1.1.2
      - DNS2=1.0.0.2
how does this work with the latest pihole image it states you need to have 127.0.0.1 as the first dns entry ?

**Comment by g0ldfngr** [comment]
My pihole is working, with no issues with that config. I'm also using my pihole as my DHCP server so I can see the computer names in the pihole dashboard.

My pihole /etc/resolve.conf:
`nameserver 127.0.0.11`
`options ndots:0`

**Comment by g0ldfngr** [comment]
Make sure you put your host IP address in your local /etc/resolv.conf this is the IP address of your Ubuntu server.

**Comment by sudo-kraken** [comment]
So in my host resolv.conf it should have my router up and host ip?

**Comment by g0ldfngr** [comment]
My host resolv.conf only has my host IP.

**Comment by sudo-kraken** [comment]
Did you run any of the above commands ?

**Comment by sudo-kraken** [comment]
Ive updated the resolv.conf to my server ip and rebooted with the same yml as you but pihole logs still show the dns service failed?

**Comment by g0ldfngr** [comment]
Let me see if I can lab this out and check the process.

**Comment by sudo-kraken** [comment]
Thank you so much

**Comment by sudo-kraken** [comment]
It also seems adding the network manager part above auto replaces the resolvconf to the router ip something to consider in the lab

**Comment by sudo-kraken** [comment]
Just to update I have ran the following and got it working again.

Commented out the dns=default in the NetworkManager conf file
sudo apt-get remove --purge resolvconf && sudo apt-get install resolvconf
This put my resolv.conf back in place, I then editted it to only contain my ip for my server, then stoped and disabled the systemd-resolved.service and edited my compose file to match yours but added in the below.
dns: 127.0.0.1

once it came up it worked and then I rebooted for good measure, but on reboot it still works however the /etc/resolv.conf is now empty of any entries except for commented out ones which is odd, but it still seems to be working.

Not sure which part has got it working but I am unsure as to why its working, could just use some pointers from you to get the static ips working along with cloudflared for dnssec

**Comment by g0ldfngr** [comment]
Thanks for pointing out this issue to me and forcing me to lab out my project.  I found tons of errors. It looks like I'm missing a few files for the DHCP portion to work properly and the log file directory was wrong.  Once I fixed that it seams to start up.  I'm not sure how my prod one is working. I will be updating files here shortly.

**Comment by Joeharrison94** [comment]
@adradloff no problem, I also spotted in the readme youll need to update the docker exec switch to -ti :) and I am trying to get this working with cloudflared it seems to be ok apart from in the pi logs are saying it has an issue with "dnsmasq: bad address at line 42 of /etc/dnsmasq.d/01-pihole.conf" when I check it the entry is the cloudflared one which I assigned as 10.0.0.40#5054 so I cant work out why its not liking it? any ideas

**Comment by sudo-kraken** [comment]
it also broke grafana, did you have this issue

**Comment by sudo-kraken** [comment]
and oauth is dead and hydra by the looks of it

**Comment by g0ldfngr** [comment]
> @adradloff no problem, I also spotted in the readme youll need to update the docker exec switch to -ti :)

I'm not sure what you are saying here. can you elaborate?

**Comment by g0ldfngr** [comment]
I'm not using Grafana, so I don't know.  Oauth is working just fine for me in my lab.

**Comment by sudo-kraken** [comment]
I’ve got it all working smoothly the only thing that breaks grafana is when I use cloudflared as well I think it breaks the dns for that container as it’s saying it can’t contact grafana.com to pull its dependencies
